services:
    phpmemcachedadmin:
        container_name: "phpmemcachedadmin"
        build:
            context: "."
            dockerfile: "./docker/apache2/Dockerfile"
        volumes:
            - "./:/var/www/"
            - "./docker/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro"
        ports:
            - "80:80"
